// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg3oo3lKWAP_dw-SztrPA2kNObvDEFUuQ',
    appId: '1:565051609831:web:06247d2acb9e314125c842',
    messagingSenderId: '565051609831',
    projectId: 'epago-b4676',
    authDomain: 'epago-b4676.firebaseapp.com',
    storageBucket: 'epago-b4676.firebasestorage.app',
    measurementId: 'G-ZR6F37KE2Z',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAENtnRZnIl5aPo7aAEPnRyJ-9vzgNzpl4',
    appId: '1:565051609831:ios:9c86a514609c4cb225c842',
    messagingSenderId: '565051609831',
    projectId: 'epago-b4676',
    storageBucket: 'epago-b4676.firebasestorage.app',
    iosBundleId: 'com.example.thethisPlatform',
  );

}